export default {
  cover_paperCategory: [
    {
      default: true,
      name: 'Estucado brillo',
      code: 'estucado-brillo',
      group: '1',
    },
    {
      name: 'Estucado mate',
      code: 'estucado-mate',
      group: '1',
    },
  ],

  cover_paperType: {
    'estucado-brillo': [
      {
        default: true,
        name: '115 gr',
        code: 'estucado-brillo-115',
        description: '115 gr',
        group: '1',
        factor: 1,
        weight: 115,
      },
      {
        name: '130 gr',
        code: 'estucado-brillo-130',
        description: '130 gr',
        group: '1',
        factor: 1,
        weight: 130,
      },
      {
        name: '150 gr',
        code: 'estucado-brillo-150',
        description: '150 gr',
        group: '1',
        factor: 1,
        weight: 150,
      },
      {
        name: '200 gr',
        code: 'estucado-brillo-200',
        description: '200 gr',
        group: '1',
        factor: 1,
        weight: 200,
      },
      {
        name: '250 gr',
        code: 'estucado-brillo-250',
        description: '250 gr',
        group: '1',
        factor: 1,
        weight: 250,
      },
    ],
    'estucado-mate': [
      {
        default: true,
        name: '115 gr',
        code: 'estucado-mate-115',
        description: '115 gr',
        group: '1',
        factor: 1,
        weight: 115,
      },
      {
        name: '130 gr',
        code: 'estucado-mate-130',
        description: '130 gr',
        group: '1',
        factor: 1,
        weight: 130,
      },
      {
        name: '150 gr',
        code: 'estucado-mate-150',
        description: '150 gr',
        group: '1',
        factor: 1,
        weight: 150,
      },
      {
        name: '200 gr',
        code: 'estucado-mate-200',
        description: '200 gr',
        group: '1',
        factor: 1,
        weight: 200,
      },
      {
        name: '250 gr',
        code: 'estucado-mate-250',
        description: '250 gr',
        group: '1',
        factor: 1,
        weight: 250,
      },
    ],
  },

  finishType: [
    {
      default: true,
      name: 'Sin acabado',
      code: 'sin-acabado',
    },
    {
      name: 'Laminado mate',
      code: 'laminado-mate',
    },
    {
      name: 'Laminado brillo',
      code: 'laminado-brillo',
    },
    {
      name: 'Soft touch',
      code: 'soft-touch',
    },
  ],

  inner_paperType: {
    'estucado-brillo': [
      {
        default: true,
        name: '115 gr',
        code: 'estucado-brillo-115',
        description: '115 gr',
        group: '1',
        factor: 1,
        weight: 115,
      },
      {
        name: '130 gr',
        code: 'estucado-brillo-130',
        description: '130 gr',
        group: '1',
        factor: 1,
        weight: 130,
      },
      {
        name: '150 gr',
        code: 'estucado-brillo-150',
        description: '150 gr',
        group: '1',
        factor: 1,
        weight: 150,
      },
      {
        name: '200 gr',
        code: 'estucado-brillo-200',
        description: '200 gr',
        group: '1',
        factor: 1,
        weight: 200,
      },
      {
        name: '250 gr',
        code: 'estucado-brillo-250',
        description: '250 gr',
        group: '1',
        factor: 1,
        weight: 250,
      },
    ],
    'estucado-mate': [
      {
        default: true,
        name: '115 gr',
        code: 'estucado-mate-115',
        description: '115 gr',
        group: '1',
        factor: 1,
        weight: 115,
      },
      {
        name: '130 gr',
        code: 'estucado-mate-130',
        description: '130 gr',
        group: '1',
        factor: 1,
        weight: 130,
      },
      {
        name: '150 gr',
        code: 'estucado-mate-150',
        description: '150 gr',
        group: '1',
        factor: 1,
        weight: 150,
      },
      {
        name: '200 gr',
        code: 'estucado-mate-200',
        description: '200 gr',
        group: '1',
        factor: 1,
        weight: 200,
      },
      {
        name: '250 gr',
        code: 'estucado-mate-250',
        description: '250 gr',
        group: '1',
        factor: 1,
        weight: 250,
      },
    ],
  },

  inner_paperCategory: [
    {
      default: true,
      name: 'Estucado brillo',
      code: 'estucado-brillo',
      group: '1',
    },
    {
      name: 'Estucado mate',
      code: 'estucado-mate',
      group: '1',
    },
  ],

  format: [
    {
      default: true,
      name: 'Vertical',
      code: 'vertical',
      factor: 1,
    },
    {
      name: 'Horizontal',
      code: 'horizontal',
      factor: 1,
    },
    {
      name: 'Cuadrado',
      code: 'cuadrado',
      factor: 1,
    },
  ],

  vertical_size: [
    {
      default: true,
      name: 'A6',
      code: 'a6',
      width: 105,
      height: 148,
      factor: 1,
      description: '105x148',
      group: '1',
    },
    {
      name: 'A5',
      code: 'a5',
      factor: 1,
      description: '148x210',
      width: 148,
      height: 210,
      group: '1',
    },
    {
      name: 'A4',
      code: 'a4',
      factor: 1,
      description: '210x297',
      width: 210,
      height: 297,
      group: '1',
    },
    {
      name: '10x21',
      code: '10x21',
      description: '10x21',
      width: 100,
      height: 210,
      factor: 1,
      group: '1',
    },
  ],

  horizontal_size: [
    {
      default: true,
      name: 'A6',
      code: 'a6',
      description: '148x105',
      width: 148,
      height: 105,
      factor: 1,
      group: '1',
    },
    {
      name: 'A5',
      code: 'a5',
      description: '210x148',
      width: 210,
      height: 148,
      factor: 1,
      group: '1',
    },
    {
      name: 'A4',
      code: 'a4',
      description: '297x210',
      width: 297,
      height: 210,
      factor: 1,
      group: '1',
    },
    {
      name: '21x10',
      code: '21x10',
      description: '21x10',
      width: 210,
      height: 100,
      factor: 1,
      group: '1',
    },
  ],

  square_size: [
    {
      default: true,
      name: '12x12',
      code: '12',
      description: '12x12',
      width: 120,
      height: 120,
      factor: 1,
      group: '1',
    },
    {
      name: '10.5x10.5',
      code: '10.5',
      description: '10.5x10.5',
      width: 105,
      height: 105,
      factor: 1,
      group: '1',
    },
    {
      name: '14.8x14.8',
      code: '14.8',
      description: '14.8x14.8',
      width: 148,
      height: 148,
      factor: 1,
      group: '2',
    },
    {
      name: '21x21',
      code: '21',
      description: '21x21',
      width: 210,
      height: 210,
      factor: 1,
      group: '2',
    },
  ],

  copiesQuantity: [
    {
      default: true,
      name: '50',
      code: '50',
      factor: 1,
      group: '1',
    },
    {
      name: '100',
      code: '100',
      factor: 2,
      group: '1',
    },
    {
      name: '150',
      code: '150',
      factor: 3,
      group: '1',
    },
    {
      name: '200',
      code: '200',
      factor: 4,
      group: '1',
    },
    {
      name: '250',
      code: '250',
      factor: 5,
      group: '2',
    },
    {
      name: '300',
      code: '300',
      factor: 6,
      group: '2',
    },
    {
      name: '400',
      code: '400',
      factor: 8,
      group: '2',
    },
    {
      name: '500',
      code: '500',
      factor: 10,
      group: '2',
    },
  ],
};
